courts = [{'court_name': 'Арбитражного суда Алтайского края', 'court_code': 'А03',
           'court_address': '656015 Барнаул,просп. Ленина, 76', 'court_time_shift': 4,
           'court_phone_info': '(385-2)29-88-01', 'court_fax_info': '(385-2)29-88-29',
           'court_email': 'a03.info@arbitr.ru', 'court_website': 'http://altai-krai.arbitr.ru/',
           'court_head': 'Кулик Максим Алексеевич (и.о.)'},
          {'court_name': 'Арбитражного суда Амурской области', 'court_code': 'А04',
           'court_address': '675023 Благовещенск,ул. Ленина, 163', 'court_time_shift': 6,
           'court_phone_info': '(416-2)59-59-00', 'court_fax_info': '(416-2)51-83-48',
           'court_email': 'info@amuras.arbitr.ru', 'court_website': 'http://amuras.arbitr.ru/',
           'court_head': 'Антонова Светлана Александровна'},
          {'court_name': 'Арбитражного суда Архангельской области', 'court_code': 'А05',
           'court_address': '163000, Архангельск,ул.Логинова, д.17', 'court_time_shift': 0,
           'court_phone_info': '(8182)42-09-80', 'court_fax_info': '(8182)42-07-99\xa0',
           'court_email': 'info@arhangelsk.arbitr.ru', 'court_website': 'http://arhangelsk.arbitr.ru/',
           'court_head': 'Хромцов Виктор Николаевич\xa0'},
          {'court_name': 'Арбитражного суда Астраханской области', 'court_code': 'А06',
           'court_address': '414014 Астрахань,просп. Губернатора Анатолия Гужвина, 6', 'court_time_shift': 1,
           'court_phone_info': '(851-2)48-42-01', 'court_fax_info': '(851-2)48-23-23',
           'court_email': 'info@astrahan.arbitr.ru', 'court_website': 'http://astrahan.arbitr.ru/',
           'court_head': 'Смирников Алексей Валерьевич'},
          {'court_name': 'Арбитражного суда Белгородской области', 'court_code': 'А08',
           'court_address': '308000 Белгород,Народный бульвар, 135', 'court_time_shift': 0,
           'court_phone_info': '(4722)35-60-16', 'court_fax_info': '(4722)32-85-38',
           'court_email': 'a08.info@arbitr.ru', 'court_website': 'http://belgorod.arbitr.ru/',
           'court_head': 'Гумеров Марат Ильгизович'},
          {'court_name': 'Арбитражного суда Брянской области', 'court_code': 'А09',
           'court_address': '241050 Брянск,пер. Трудовой, 6', 'court_time_shift': 0,
           'court_phone_info': '(4832)77-09-47', 'court_fax_info': '(4832)77-09-58',
           'court_email': 'info@bryansk.arbitr.ru', 'court_website': 'http://bryansk.arbitr.ru/',
           'court_head': 'Егоров Евгений Иванович'},
          {'court_name': 'Арбитражного суда Владимирской области', 'court_code': 'А11',
           'court_address': '600005, г. Владимир,Октябрьский просп., д. 19', 'court_time_shift': 0,
           'court_phone_info': '(4922)32-29-10(4922)47-23-65', 'court_fax_info': '(4922)42-32-13',
           'court_email': 'vladimir.info@arbitr.ru', 'court_website': 'http://vladimir.arbitr.ru/',
           'court_head': 'Евсеева Людмила Николаевна (и.о.)'},
          {'court_name': 'Арбитражного суда Волгоградской области', 'court_code': 'А12',
           'court_address': '400005 Волгоград,ул. им. 7-й Гвардейской дивизии, 2', 'court_time_shift': 0,
           'court_phone_info': '(844-2)23-00-78', 'court_fax_info': '(844-2)24-04-60',
           'court_email': 'info@volgograd.arbitr.ru', 'court_website': 'http://volgograd.arbitr.ru/',
           'court_head': 'Романов Виктор Николаевич'},
          {'court_name': 'Арбитражного суда Вологодской области', 'court_code': 'А13',
           'court_address': '160000, г. Вологда,ул. Герцена, 1а', 'court_time_shift': 0,
           'court_phone_info': '(817-2)72-04-01(817-2)57-08-88', 'court_fax_info': '',
           'court_email': 'info@vologda.arbitr.ru', 'court_website': 'http://vologda.arbitr.ru/',
           'court_head': 'Чапаев Игорь Александрович'},
          {'court_name': 'Арбитражного суда Воронежской области', 'court_code': 'А14',
           'court_address': '394030 Воронеж,ул. Среднемосковская, 77', 'court_time_shift': 0,
           'court_phone_info': '(4732)59-71-81(4732)52-53-44', 'court_fax_info': '(4732)52-47-09',
           'court_email': 'info@voronej.arbitr.ru', 'court_website': 'http://voronej.arbitr.ru/',
           'court_head': 'Кочетков Александр Викторович'},
          {'court_name': 'Арбитражного суда города Москвы', 'court_code': 'А40',
           'court_address': '115225  Москва,ул. Большая Тульская, 17', 'court_time_shift': 0,
           'court_phone_info': '(495)600-96-64(495)600-99-53(495)600-99-52', 'court_fax_info': '(495)600-99-66',
           'court_email': 'info@msk.arbitr.ru', 'court_website': 'http://msk.arbitr.ru/',
           'court_head': 'Новиков Николай Алексеевич'},
          {'court_name': 'Арбитражного суда города Санкт-Петербурга и Ленинградской области', 'court_code': 'А56',
           'court_address': '191124, Санкт-Петербург,ул. Смольного, д. 6', 'court_time_shift': 0,
           'court_phone_info': '(812)643-48-18 - справочная служба', 'court_fax_info': '(812)643-48-19',
           'court_email': 'a56.info@arbitr.ru', 'court_website': 'http://spb.arbitr.ru/',
           'court_head': 'Володкина Александра Ивановна'},
          {'court_name': 'Арбитражного суда города Севастополь', 'court_code': 'А84',
           'court_address': '299011 г. Севастопольул. Л. Павличенко, 5', 'court_time_shift': 0,
           'court_phone_info': '(0692)54-34-91', 'court_fax_info': '(0692)54-34-91',
           'court_email': 'info@sevastopol.arbitr.ru', 'court_website': 'http://sevastopol.arbitr.ru/',
           'court_head': 'Акулов Александр Иванович'},
          {'court_name': 'Арбитражного суда Еврейской автономной области', 'court_code': 'А16',
           'court_address': '679016 Биробиджан,пер. Театральный, 10', 'court_time_shift': 7,
           'court_phone_info': '(426-22)4-07-00', 'court_fax_info': '(426-22)2-11-23',
           'court_email': 'info@eao.arbitr.ru', 'court_website': 'http://eao.arbitr.ru/',
           'court_head': 'Янина Светлана Владимировна'},
          {'court_name': 'Арбитражного суда  Забайкальского края', 'court_code': 'А78',
           'court_address': '672002 Чита,ул. Выставочная, 6', 'court_time_shift': 6,
           'court_phone_info': '(302-2)33-05-01', 'court_fax_info': '(302-2)33-06-33',
           'court_email': 'info@chita.arbitr.ru', 'court_website': 'http://chita.arbitr.ru/',
           'court_head': 'Ячменёв Георгий Григорьевич'},
          {'court_name': 'Арбитражного суда Ивановской области', 'court_code': 'А17',
           'court_address': '153022 Ивановоул. Б. Хмельницкого, д. 59б', 'court_time_shift': 0,
           'court_phone_info': '(4932)41-81-07', 'court_fax_info': '(4932)42-96-65',
           'court_email': 'info@ivanovo.arbitr.ru', 'court_website': 'http://ivanovo.arbitr.ru/',
           'court_head': 'Семенов Алексей Иванович'},
          {'court_name': 'Арбитражного суда Иркутской области', 'court_code': 'А19',
           'court_address': '664025 Иркутск,бульвар Гагарина, 70', 'court_time_shift': 5,
           'court_phone_info': '(395-2)254-200 - (бул. Гагарина, 70)(395-2)261-709 - ул. Дзержинского, 36А (1-ый судаебный состав по рассмотрению дел о несостоятельности (банкротстве))(395-2)254-109 - (бул. Гагарина, 70)',
           'court_fax_info': '(395-2)241-599 - (бул. Гагарина, 70)(395-2)261-761 - ул. Дзержинского, 36А (1-ый судаебный состав по рассмотрению дел о несостоятельности (банкротстве))',
           'court_email': 'info@irkutsk.arbitr.ru', 'court_website': 'http://irkutsk.arbitr.ru/',
           'court_head': 'Алдатов Батраз Константинович'},
          {'court_name': 'Арбитражного суда Кабардино-Балкарской Республики', 'court_code': 'А20',
           'court_address': '360022, Кабардино-Балкарская Республика, г.Нальчик,ул.Мечникова, 130а',
           'court_time_shift': 0, 'court_phone_info': '(8662)77-31-96', 'court_fax_info': '(8662)44-02-23',
           'court_email': 'mail@askb.arbitr.ru', 'court_website': 'http://askb.arbitr.ru/',
           'court_head': 'Мельников Игорь Михайлович'},
          {'court_name': 'Арбитражного суда Калининградской области', 'court_code': 'А21',
           'court_address': '236040 Калининград,ул. Рокоссовского, 2-4', 'court_time_shift': -1,
           'court_phone_info': '(4012)57-22-22', 'court_fax_info': '(4012)53-04-84',
           'court_email': 'kaliningrad.info@arbitr.ru', 'court_website': 'http://kaliningrad.arbitr.ru/',
           'court_head': 'Бандуров Дмитрий Николаевич'},
          {'court_name': 'Арбитражного суда Калужской области', 'court_code': 'А23',
           'court_address': '248000, г. Калуга,ул. Ленина, 90', 'court_time_shift': 0,
           'court_phone_info': '(4842)505-992(4842)505-985', 'court_fax_info': '(4842)59-94-57',
           'court_email': 'kaluga.info@arbitr.ru', 'court_website': 'http://kaluga.arbitr.ru/',
           'court_head': 'Туманов Владислав Николаевич'},
          {'court_name': 'Арбитражного суда Камчатского края', 'court_code': 'А24',
           'court_address': '683009,  Петропавловск-Камчатский,ул. Академика Курчатова, 2', 'court_time_shift': 9,
           'court_phone_info': '(415-2)219-200', 'court_fax_info': '(415-2)219-219',
           'court_email': 'info@kamchatka.arbitr.ru', 'court_website': 'http://kamchatka.arbitr.ru/',
           'court_head': 'Курмачев Денис Валерьевич'},
          {'court_name': 'Арбитражного суда Карачаево-Черкесской Республики', 'court_code': 'А25',
           'court_address': '369000 Черкесск,ул. Ленина, д.9', 'court_time_shift': 0,
           'court_phone_info': '(8782)26-36-39', 'court_fax_info': '(8782)26-36-39',
           'court_email': 'info@askchr.arbitr.ru', 'court_website': 'http://askchr.arbitr.ru/',
           'court_head': 'Мельников Игорь Михайлович'},
          {'court_name': 'Арбитражного суда Кемеровской области', 'court_code': 'А27',
           'court_address': '650000, г. Кемерово,ул. Красная, д.8', 'court_time_shift': 4,
           'court_phone_info': '(384-2)45-10-16', 'court_fax_info': '', 'court_email': 'info@kemerovo.arbitr.ru',
           'court_website': 'http://kemerovo.arbitr.ru/', 'court_head': 'Кощеев Константин Леонидович'},
          {'court_name': 'Арбитражного суда Кировской области', 'court_code': 'А28',
           'court_address': '610017 Киров,ул. К.Либкнехта, 102', 'court_time_shift': 0,
           'court_phone_info': '(833-2)70-92-11(833-2)70-91-18', 'court_fax_info': '',
           'court_email': 'info@kirov.arbitr.ru', 'court_website': 'http://kirov.arbitr.ru/',
           'court_head': 'Мартынов Сергей Васильевич'},
          {'court_name': 'Арбитражного суда Костромской области', 'court_code': 'А31',
           'court_address': '156000, г. Кострома,ул. Долматова, д. 2', 'court_time_shift': 0,
           'court_phone_info': '(4942)45-10-31(4942)31-37-79', 'court_fax_info': '(4942)35-19-44',
           'court_email': 'info@kostroma.arbitr.ru', 'court_website': 'http://kostroma.arbitr.ru/',
           'court_head': 'Цветков Сергей Владимирович'},
          {'court_name': 'Арбитражного суда Краснодарского края', 'court_code': 'А32',
           'court_address': '350063, г. Краснодар,ул. Постовая, д. 32', 'court_time_shift': 0,
           'court_phone_info': '(861)293-81-03(861)293-81-00(861)293-00-00', 'court_fax_info': '(861)992-38-22',
           'court_email': 'info@krasnodar.arbitr.ru', 'court_website': 'http://krasnodar.arbitr.ru/',
           'court_head': 'Егоров Алексей Евгеньевич'},
          {'court_name': 'Арбитражного суда Красноярского края', 'court_code': 'А33',
           'court_address': '660049 г. Красноярск,ул. Ленина, д. 1', 'court_time_shift': 4,
           'court_phone_info': '(391)226-59-00(391)226-59-30', 'court_fax_info': '(391)226-59-34(391)226-59-02',
           'court_email': 'info@krasnoyarsk.arbitr.ru', 'court_website': 'http://krasnoyarsk.arbitr.ru/',
           'court_head': 'Касьянова Лариса Анатольевна'},
          {'court_name': 'Арбитражного суда Курганской области', 'court_code': 'А34',
           'court_address': '640002 Курган,ул. Климова, 62', 'court_time_shift': 2,
           'court_phone_info': '(352-2)46-64-84', 'court_fax_info': '(352-2)46-38-07',
           'court_email': 'info@kurgan.arbitr.ru', 'court_website': 'http://kurgan.arbitr.ru/',
           'court_head': 'Доставалов Вячеслав Валерьевич'},
          {'court_name': 'Арбитражного суда Курской области', 'court_code': 'А35',
           'court_address': '305004 Курск,ул. К.Маркса, 25', 'court_time_shift': 0,
           'court_phone_info': '(4712)53-69-36', 'court_fax_info': '(4712)58-04-32',
           'court_email': 'info@kursk.arbitr.ru', 'court_website': 'http://kursk.arbitr.ru/',
           'court_head': 'и.о. Председателя судаа Шумаков Александр Иванович'},
          {'court_name': 'Арбитражного суда Липецкой области', 'court_code': 'А36',
           'court_address': '398019, г. Липецк,пл. Петра Великого, д. 7', 'court_time_shift': 0,
           'court_phone_info': '(4742)202-073(4742)202-055', 'court_fax_info': '(4742)202-044(4742)202-055',
           'court_email': 'info@lipetsk.arbitr.ru', 'court_website': 'http://lipetsk.arbitr.ru/',
           'court_head': 'Щедухина Татьяна Михайловна'},
          {'court_name': 'Арбитражного суда Магаданской области', 'court_code': 'А37',
           'court_address': '685000 Магадан,просп. К.Маркса, 62', 'court_time_shift': 7,
           'court_phone_info': '(413-2)65-03-80', 'court_fax_info': '(413-2)65-03-80',
           'court_email': 'info@magadan.arbitr.ru', 'court_website': 'http://magadan.arbitr.ru/',
           'court_head': 'Липин Владимир Владимирович'},
          {'court_name': 'Арбитражного суда Московской области', 'court_code': 'А41',
           'court_address': '107053 Москва, ГСП-6,просп. Академика Сахарова, 18', 'court_time_shift': 0,
           'court_phone_info': '(499)975-29-46', 'court_fax_info': '(499)975-13-83',
           'court_email': 'info@asmo.arbitr.ru', 'court_website': 'http://asmo.arbitr.ru/',
           'court_head': 'И.о. Смирнов Олег Валентинович'},
          {'court_name': 'Арбитражного суда Мурманской области', 'court_code': 'А42',
           'court_address': '183038 Мурманск,ул. Книповича, 20', 'court_time_shift': 0,
           'court_phone_info': '(815-2)45-36-18', 'court_fax_info': '(815-2)44-26-51',
           'court_email': 'murmansk.info@arbitr.ru', 'court_website': 'http://murmansk.arbitr.ru/',
           'court_head': 'Драчен Артем Васильевич'},
          {'court_name': 'Арбитражного суда Нижегородской области', 'court_code': 'А43',
           'court_address': '603082 Нижний Новгород,Кремль, корп. 9', 'court_time_shift': 0,
           'court_phone_info': '(831)439-10-40(831)439-15-70', 'court_fax_info': '(831)439-15-38',
           'court_email': 'info@nnov.arbitr.ru', 'court_website': 'http://nnov.arbitr.ru/',
           'court_head': 'Санинский Роман Александрович'},
          {'court_name': 'Арбитражного суда Новгородской области', 'court_code': 'А44',
           'court_address': '173020, Новгородская область, Великий Новгород,ул. Большая Московская, 73',
           'court_time_shift': 0, 'court_phone_info': '(8162)94-51-35', 'court_fax_info': '(8162)94-50-88',
           'court_email': 'info@novgorod.arbitr.ru', 'court_website': 'http://novgorod.arbitr.ru/',
           'court_head': 'И.о. Козлова Ирина Вячеславовна'},
          {'court_name': 'Арбитражного суда Новосибирской области', 'court_code': 'А45',
           'court_address': '630102 Новосибирск,ул. Нижегородская, 6', 'court_time_shift': 4,
           'court_phone_info': '(383)269-69-90(383)269-69-91', 'court_fax_info': '(383)269-68-80',
           'court_email': 'info@novosib.arbitr.ru', 'court_website': 'http://novosib.arbitr.ru/',
           'court_head': 'Козлова Елена Петровна'},
          {'court_name': 'Арбитражного суда Омской области', 'court_code': 'А46',
           'court_address': '644024 Омскул. Учебная, 51', 'court_time_shift': 3, 'court_phone_info': '(381-2)31-56-51',
           'court_fax_info': '(381-2)53-02-05', 'court_email': 'info@omsk.arbitr.ru',
           'court_website': 'http://omsk.arbitr.ru/', 'court_head': 'Поликарпов Евгений Вячеславович'},
          {'court_name': 'Арбитражного суда Оренбургской области', 'court_code': 'А47',
           'court_address': '460024 Оренбург,ул. Краснознаменная, 56', 'court_time_shift': 2,
           'court_phone_info': '(353-2)45-30-33', 'court_fax_info': '(353-2)45-25-33',
           'court_email': 'orenburg.info@ARBITR.RUinfo@orenburg.arbitr.ru',
           'court_website': 'http://orenburg.arbitr.ru/', 'court_head': 'Штырник Валентина Михайловна'},
          {'court_name': 'Арбитражного суда Орловской области', 'court_code': 'А48',
           'court_address': '302000 Орел,ул. М.Горького, 42', 'court_time_shift': 0,
           'court_phone_info': '(4862)43-24-44', 'court_fax_info': '(4862)43-24-66',
           'court_email': 'info@orel.arbitr.ru', 'court_website': 'http://orel.arbitr.ru/',
           'court_head': 'Шурыгин Сергей Дмитриевич'},
          {'court_name': 'Арбитражного суда Пензенской области', 'court_code': 'А49',
           'court_address': '440000 Пенза,ул. Кирова, 35/39', 'court_time_shift': 0,
           'court_phone_info': '(841-2)52-99-09', 'court_fax_info': '(841-2)56-11-93',
           'court_email': 'penza.info@ARBITR.RU', 'court_website': 'http://penza.arbitr.ru/',
           'court_head': 'Радин Станислав Юрьевич'},
          {'court_name': 'Арбитражного суда Пермского края', 'court_code': 'А50',
           'court_address': '614068 Пермь,ул. Екатерининская, 177', 'court_time_shift': 2,
           'court_phone_info': '(342)217-50-00', 'court_fax_info': '(342)236-80-02',
           'court_email': 'info@perm.arbitr.ru', 'court_website': 'http://perm.arbitr.ru/',
           'court_head': 'Мещерякова Татьяна Игоревна'},
          {'court_name': 'Арбитражного суда Приморского края', 'court_code': 'А51',
           'court_address': '690091, Владивосток,ул. Октябрьская, д. 27', 'court_time_shift': 7,
           'court_phone_info': '(423-2)21-53-76(423-2)21-54-05', 'court_fax_info': '(423-2)26-62-81',
           'court_email': 'info@primkray.arbitr.ru', 'court_website': 'http://primkray.arbitr.ru/',
           'court_head': 'И.о. председателя: Сеитов Эльдар Муталибович'},
          {'court_name': 'Арбитражного суда Псковской области', 'court_code': 'А52',
           'court_address': '180000 Псков,ул. Свердлова, 36', 'court_time_shift': 0,
           'court_phone_info': '(8112)75-29-62', 'court_fax_info': '(8112)72-14-30',
           'court_email': 'info@pskov.arbitr.ru', 'court_website': 'http://pskov.arbitr.ru/',
           'court_head': 'Тимаев Федор Иванович'},
          {'court_name': 'Постоянное судаебное присутствие Арбитражного судаа Пермского края в г. Кудымкар',
           'court_code': 'А50П', 'court_address': '619000, Пермский край, г. Кудымкар,ул. Лихачева, 45',
           'court_time_shift': 2, 'court_phone_info': '(34260)4-87-97(34260)4-15-65',
           'court_fax_info': '(34260)4-15-65',
           'court_email': 'a50.psp@arbitr.rua50.8sostav@arbitr.ru - для направления сторонами документов в рамках рассматриваемых дел',
           'court_website': 'http://www.perm.arbitr.ru/', 'court_head': 'Мещерякова Татьяна Игоревна'},
          {
              'court_name': 'Постоянное судаебное присутствие Арбитражного судаа Архангельской области в Ненецком автономном округе (г. Нарьян-Мар)',
              'court_code': 'А05П', 'court_address': '166000, г. Нарьян-Мар,ул. Смидовича, д. 4.',
              'court_time_shift': 0, 'court_phone_info': '(81853)4-05-22', 'court_fax_info': '',
              'court_email': 'info@arhangelsk.arbitr.ru', 'court_website': 'http://arhangelsk.arbitr.ru/',
              'court_head': ''},
          {'court_name': 'Арбитражного суда Республики Адыгея', 'court_code': 'А01',
           'court_address': '385000, Республика Адыгея, г. Майкоп,ул. Краснооктябрьская, 15',
           'court_time_shift': 0, 'court_phone_info': '(8772)52-63-34(8772)57-16-26',
           'court_fax_info': '(8772)52-76-80', 'court_email': 'info@adyg.arbitr.ru',
           'court_website': 'http://adyg.arbitr.ru/',
           'court_head': 'Боровик Александр Михайлович'},
          {'court_name': 'Арбитражного суда Республики Алтай', 'court_code': 'А02',
           'court_address': '649000, Республика Алтай, Горно-Алтайск,ул. Ленкина, 4', 'court_time_shift': 4,
           'court_phone_info': '(388-22)4-76-58 - для справок, канцелярия(388-22)4-77-17 - приёмная председателя судаа(388-22)4-77-03',
           'court_fax_info': '(388-22)4-77-17(388-22)4-77-10', 'court_email': 'info@altai.arbitr.ru',
           'court_website': 'http://altai.arbitr.ru/', 'court_head': 'И.о. Гуткович Евгений Михелевич'},
          {'court_name': 'Арбитражного суда Республики Башкортостан', 'court_code': 'А07',
           'court_address': '450057 Уфа,ул. Октябрьской Революции, 63а', 'court_time_shift': 2,
           'court_phone_info': '(347)272-59-60', 'court_fax_info': '(347)272-27-40',
           'court_email': 'a07.info@arbitr.ru', 'court_website': 'http://ufa.arbitr.ru/',
           'court_head': 'Архиереев Николай Викторович'},
          {'court_name': 'Арбитражного суда Республики Бурятия', 'court_code': 'А10',
           'court_address': '670000 Улан-Удэ,ул. Коммунистическая, 52', 'court_time_shift': 5,
           'court_phone_info': '(301-2)28-65-02(301-2)28-65-28', 'court_fax_info': '(301-2)21-60-23',
           'court_email': 'buryatia.info@arbitr.ru', 'court_website': 'http://buryatia.arbitr.ru/',
           'court_head': 'Сонин Анатолий Анатольевич'},
          {'court_name': 'Арбитражного суда Республики Дагестан', 'court_code': 'А15',
           'court_address': '367009 Махачкала,ул. Керимова, 7', 'court_time_shift': 0,
           'court_phone_info': '(872-2)69-49-68', 'court_fax_info': '(872-2)69-49-67',
           'court_email': 'info@mahachkala.arbitr.ru', 'court_website': 'http://mahachkala.arbitr.ru/',
           'court_head': 'Исаев Магомед Салихович'},
          {'court_name': 'Арбитражного суда Республики Ингушетия', 'court_code': 'А18',
           'court_address': '386101 Назрань,просп. им. Идриса Базоркина, 44', 'court_time_shift': 0,
           'court_phone_info': '(873-2)22-40-77(873-2)22-40-57(873-2)22-42-71(873-2)22-71-07',
           'court_fax_info': '(873-2)22-40-80', 'court_email': 'ingushetia.info@arbitr.ru',
           'court_website': 'http://ingushetia.arbitr.ru/', 'court_head': 'и.о. Мержоев Магомет Мухтарович'},
          {'court_name': 'Арбитражного суда Республики Калмыкия', 'court_code': 'А22',
           'court_address': '358000 Элиста,ул. Сусеева,10', 'court_time_shift': 0,
           'court_phone_info': '(84722)33166 - Канцелярия(84722)4-17-17', 'court_fax_info': '(84722)4-17-20',
           'court_email': 'info@kalmyk.arbitr.ru', 'court_website': 'http://kalmyk.arbitr.ru/',
           'court_head': 'И.о. председателя Садваев Бадма Бадмаевич'},
          {'court_name': 'Арбитражного суда Республики Карелия', 'court_code': 'А26',
           'court_address': '185910 Петрозаводск,ул. Красноармейская, 24а', 'court_time_shift': 0,
           'court_phone_info': '(814-2)79-05-90(814-2)79-05-91(814-2)79-05-09', 'court_fax_info': '(814-2)79-06-25',
           'court_email': 'info@karelia.arbitr.ru', 'court_website': 'http://karelia.arbitr.ru/',
           'court_head': 'Кезик Татьяна Васильевна'},
          {'court_name': 'Арбитражного суда Республики Коми', 'court_code': 'А29',
           'court_address': '167000, г. Сыктывкар,ул. Ленина, д. 60', 'court_time_shift': 0,
           'court_phone_info': '(821-2)30-08-00', 'court_fax_info': '(821-2)30-08-10',
           'court_email': 'info@komi.arbitr.ru', 'court_website': 'http://komi.arbitr.ru/',
           'court_head': 'Чернышов Дмитрий Васильевич'},
          {'court_name': 'Арбитражного суда Республики Крым', 'court_code': 'А83',
           'court_address': 'г. Симферополь, Республика Крым, 295000ул. Александра Невского, д. 29/11',
           'court_time_shift': 0, 'court_phone_info': '(3652)550-113(3652)550-101 - Канцелярия',
           'court_fax_info': '(3652)550-155', 'court_email': 'info@crimea.arbitr.ru',
           'court_website': 'http://crimea.arbitr.ru/', 'court_head': 'Мартыненко Юлия Владимировна'},
          {'court_name': 'Арбитражного суда Республики Марий Эл', 'court_code': 'А38',
           'court_address': '424002 Йошкар-Ола,Ленинский просп., 40', 'court_time_shift': 0,
           'court_phone_info': '(836-2)69-33-42(836-2)69-33-00', 'court_fax_info': '(836-2)56-58-48',
           'court_email': 'mari-el.info@arbitr.ru', 'court_website': 'http://mari-el.arbitr.ru/',
           'court_head': 'Рогожина Людмила Васильевна'},
          {'court_name': 'Арбитражного суда Республики Мордовия', 'court_code': 'А39',
           'court_address': '430030 Саранск,ул. Полежаева, дом 177', 'court_time_shift': 0,
           'court_phone_info': '(834-2)24-08-83 - Приёмная', 'court_fax_info': '(834-2)29-28-91',
           'court_email': 'info@asrm.arbitr.ru', 'court_website': 'http://asrm.arbitr.ru/',
           'court_head': 'Александров Сергей Васильевич'},
          {'court_name': 'Арбитражного суда Республики Саха (Якутия)', 'court_code': 'А58',
           'court_address': '677980 Якутск,ул. Курашова, 28', 'court_time_shift': 6,
           'court_phone_info': '(411-2)34-05-80', 'court_fax_info': '(411-2)42-05-32',
           'court_email': 'info@yakutsk.arbitr.ru', 'court_website': 'http://yakutsk.arbitr.ru/',
           'court_head': 'Макаров Игорь Владимирович'},
          {'court_name': 'Арбитражного суда Республики Северная Осетия-Алания', 'court_code': 'А61',
           'court_address': '362040 Владикавказ,пл. Свободы, 5', 'court_time_shift': 0,
           'court_phone_info': '(867-2)53-71-17', 'court_fax_info': '(867-2)53-95-38',
           'court_email': 'info@alania.arbitr.ru', 'court_website': 'http://alania.arbitr.ru/',
           'court_head': 'Носенко Марина Сергеевна'},
          {'court_name': 'Арбитражного суда Республики Татарстан', 'court_code': 'А65',
           'court_address': '420107 Казань,ул.Ново-Песочная, д.40', 'court_time_shift': 0,
           'court_phone_info': '(843)533-50-00', 'court_fax_info': '(843)533-50-00',
           'court_email': 'info@tatarstan.arbitr.ru', 'court_website': 'http://tatarstan.arbitr.ru/',
           'court_head': 'Боровков Максим Сергеевич'},
          {'court_name': 'Арбитражного суда Республики Тыва', 'court_code': 'А69',
           'court_address': '667000, Республика Тыва, г. Кызыл,ул. Кочетова, 91.', 'court_time_shift': 4,
           'court_phone_info': '(394-22)9-65-01 - приёмная(394-22)2-31-72', 'court_fax_info': '(394-22)2-11-96',
           'court_email': 'info@tyva.arbitr.ru', 'court_website': 'http://tyva.arbitr.ru/',
           'court_head': 'Ажи Владимир Алдын-оолович'},
          {'court_name': 'Арбитражного суда Республики Хакасия', 'court_code': 'А74',
           'court_address': '655017 Абакан,ул.Крылова, 74, а/я 147', 'court_time_shift': 4,
           'court_phone_info': '(390-2)29-95-00 - Приёмная(390-2)29-95-02', 'court_fax_info': '(390-2)28-81-55',
           'court_email': 'info@khakasia.arbitr.ru', 'court_website': 'http://khakasia.arbitr.ru/',
           'court_head': 'Ципляков Валерий Владимирович'},
          {'court_name': 'Арбитражного суда Ростовской области', 'court_code': 'А53',
           'court_address': '344002 Ростов-на-Дону,ул. Станиславского, 10/11-13', 'court_time_shift': 0,
           'court_phone_info': '(863)282-84-44(863)282-84-48', 'court_fax_info': '(863)262-44-94(863)269-47-64',
           'court_email': 'info@rostov.arbitr.ru', 'court_website': 'http://rostov.arbitr.ru/',
           'court_head': 'Мишаков Олег Григорьевич'},
          {'court_name': 'Арбитражного суда Рязанской области', 'court_code': 'А54',
           'court_address': '390000 Рязань,ул. Почтовая, 43/44', 'court_time_shift': 0,
           'court_phone_info': '(4912)20-95-00', 'court_fax_info': '(4912)27-51-08',
           'court_email': 'info@ryazan.arbitr.ru', 'court_website': 'http://ryazan.arbitr.ru/',
           'court_head': 'Митяева Лариса Игоревна'},
          {'court_name': 'Арбитражного суда Самарской области', 'court_code': 'А55',
           'court_address': '443001 Самара,ул. Самарская, 203Б', 'court_time_shift': 1,
           'court_phone_info': '(846)226-56-17(846)207-55-15', 'court_fax_info': '',
           'court_email': 'info@samara.arbitr.ru', 'court_website': 'http://samara.arbitr.ru/',
           'court_head': 'Каплин Сергей Юрьевич'},
          {'court_name': 'Арбитражного суда Саратовской области', 'court_code': 'А57',
           'court_address': '410002,  Саратов,ул.Бабушкин Взвоз, д.1', 'court_time_shift': 1,
           'court_phone_info': '(845-2)98-39-39(845-2)98-39-00', 'court_fax_info': '(845-2)98-39-57',
           'court_email': 'info@saratov.arbitr.ru', 'court_website': 'http://saratov.arbitr.ru/',
           'court_head': 'Горябин Алексей Анатольевич'},
          {'court_name': 'Арбитражного суда Сахалинской области', 'court_code': 'А59',
           'court_address': '693000 Южно-Сахалинск,пр.Коммунистический, 28', 'court_time_shift': 8,
           'court_phone_info': '(4242)46-09-45 - канцелярия(4242)46-09-03 - приемная',
           'court_fax_info': '(4242)46-09-52', 'court_email': 'info@sakhalin.arbitr.ru',
           'court_website': 'http://sakhalin.arbitr.ru/', 'court_head': 'Шилов Александр Владимирович'},
          {'court_name': 'Арбитражного суда Свердловской области', 'court_code': 'А60',
           'court_address': '620075 Екатеринбург,ул. Шарташская, д. 4', 'court_time_shift': 2,
           'court_phone_info': '(343)371-42-50(343)376-10-76', 'court_fax_info': '(343)371-40-20',
           'court_email': 'info@ekaterinburg.arbitr.ru', 'court_website': 'http://ekaterinburg.arbitr.ru/',
           'court_head': 'Сидоркин Станислав Владиславович'},
          {'court_name': 'Арбитражного суда Смоленской области', 'court_code': 'А62',
           'court_address': '214001 Смоленск,ул. Большая Советская 30/11', 'court_time_shift': 0,
           'court_phone_info': '(4812)24-47-72(4812)24-47-71', 'court_fax_info': '(4812)61-04-16',
           'court_email': 'info@smolensk.arbitr.ru', 'court_website': 'http://smolensk.arbitr.ru/',
           'court_head': 'Пузаненков Юрий Алексеевич'},
          {'court_name': 'Арбитражного суда Ставропольского края', 'court_code': 'А63',
           'court_address': '355029 Ставрополь,ул. Мира, 458б', 'court_time_shift': 0,
           'court_phone_info': '(865-2)20-54-22', 'court_fax_info': '(865-2)71-40-60',
           'court_email': 'info@stavropol.arbitr.ru', 'court_website': 'http://stavropol.arbitr.ru/',
           'court_head': 'Лысенко Лариса Анатольевна'},
          {'court_name': 'Арбитражного суда Тамбовской области', 'court_code': 'А64',
           'court_address': '392020 Тамбов,ул. Пензенская, 67/12', 'court_time_shift': 0,
           'court_phone_info': '(4752)47-70-55', 'court_fax_info': '(4752)47-70-10',
           'court_email': 'tambov.info@arbitr.ru', 'court_website': 'http://tambov.arbitr.ru/',
           'court_head': 'Соловьева Оксана Викторовна'},
          {'court_name': 'Арбитражного суда Тверской области', 'court_code': 'А66',
           'court_address': '170100,  Тверь,площадь Святого Благоверного Князя Михаила Тверского, д. 5',
           'court_time_shift': 0, 'court_phone_info': '(4822)390-255(4822)390-294(4822)390-276', 'court_fax_info': '',
           'court_email': 'info@tver.arbitr.ru', 'court_website': 'http://tver.arbitr.ru/',
           'court_head': 'Романова Елена Викторовна'},
          {'court_name': 'Арбитражного суда Томской области', 'court_code': 'А67',
           'court_address': '634050 Томск,пр. Кирова, 10', 'court_time_shift': 4,
           'court_phone_info': '(3822)284-083 - канцелярия(3822)284-000 - приёмная(3822)284-142 - канцелярия административной коллегии',
           'court_fax_info': '(3822)284-077(3822)284-147 - факс административной коллегии',
           'court_email': 'info@tomsk.arbitr.ru', 'court_website': 'http://tomsk.arbitr.ru/',
           'court_head': 'Янущик Дмитрий Иосифович'},
          {'court_name': 'Арбитражного суда Тульской области', 'court_code': 'А68',
           'court_address': '300041,  г. Тула,Красноармейский проспект, д. 5', 'court_time_shift': 0,
           'court_phone_info': '(4872)250-800', 'court_fax_info': '(4872)250-800', 'court_email': 'a68.info@arbitr.ru',
           'court_website': 'http://tula.arbitr.ru/', 'court_head': 'Филина Ирина Леонидовна'},
          {'court_name': 'Арбитражного суда Тюменской области', 'court_code': 'А70',
           'court_address': '625052, г. Тюмень,ул. Ленина, д. 74', 'court_time_shift': 2,
           'court_phone_info': '(345-2)25-81-13(345-2)25-81-21', 'court_fax_info': '(345-2)45-02-07',
           'court_email': 'info@tumen.arbitr.ru', 'court_website': 'http://tumen.arbitr.ru/',
           'court_head': 'Финько Олег Иванович'},
          {'court_name': 'Арбитражного суда Удмуртской Республики', 'court_code': 'А71',
           'court_address': '426011, Ижевск,ул. Ломоносова, 5', 'court_time_shift': 1,
           'court_phone_info': '(3412)602-628(3412)602-643(3412)602-620', 'court_fax_info': '(3412)602-628',
           'court_email': 'info@udmurtiya.arbitr.ru', 'court_website': 'http://udmurtiya.arbitr.ru/',
           'court_head': 'Сердитова Екатерина Николаевна'},
          {'court_name': 'Арбитражного суда Ульяновской области', 'court_code': 'А72',
           'court_address': '432068, г.  Ульяновск,ул. Железнодорожная, д. 14', 'court_time_shift': 1,
           'court_phone_info': '(8422)33-46-08(8422)33-46-09', 'court_fax_info': '(8422)32-54-54',
           'court_email': 'info@ulyanovsk.arbitr.ru', 'court_website': 'http://ulyanovsk.arbitr.ru/',
           'court_head': 'Топоров Андрей Викторович'},
          {'court_name': 'Арбитражного суда Хабаровского края', 'court_code': 'А73',
           'court_address': '680030 Хабаровск,ул. Ленина, 37', 'court_time_shift': 7,
           'court_phone_info': '(4212)91-08-31(4212)91-08-27', 'court_fax_info': '(4212)91-08-26',
           'court_email': 'info@khabarovsk.arbitr.ru', 'court_website': 'http://khabarovsk.arbitr.ru/',
           'court_head': 'Софрина Зоя Федоровна'},
          {'court_name': 'Арбитражного суда Ханты-Мансийского автономного округа - Югры', 'court_code': 'А75',
           'court_address': '628011 Ханты-Мансийский автономный округ - ЮГРА,Ханты-Мансийск, ул. Мира, 27',
           'court_time_shift': 2, 'court_phone_info': '(3467)95-88-74(3467)95-88-71 - канцелярия судаа',
           'court_fax_info': '(3467)95-88-04', 'court_email': 'hmao.info@arbitr.ru',
           'court_website': 'http://hmao.arbitr.ru/', 'court_head': 'Лисянский Денис Павлович'},
          {'court_name': 'Арбитражного суда Челябинской области', 'court_code': 'А76',
           'court_address': '454091 Челябинск,ул. Воровского, 2', 'court_time_shift': 2,
           'court_phone_info': '(351)225-03-19', 'court_fax_info': '(351)266-72-10',
           'court_email': 'info@chel.arbitr.ru', 'court_website': 'http://chel.arbitr.ru/',
           'court_head': 'Шайхутдинов Евгений Маратович'},
          {'court_name': 'Арбитражного суда Чеченской Республики', 'court_code': 'А77',
           'court_address': '364024, Чеченская Республика, г. Грозныйул. имени Шейха Али Митаева, д. 22Б',
           'court_time_shift': 0, 'court_phone_info': '(871-2)22-26-32', 'court_fax_info': '(871-2)22-28-07',
           'court_email': 'info@chechnya.arbitr.ru', 'court_website': 'http://chechnya.arbitr.ru/',
           'court_head': 'Хаджиев Тимерлан Асламбекович'},
          {'court_name': 'Арбитражного суда Чувашской Республики - Чувашии', 'court_code': 'А79',
           'court_address': '428000 Чебоксары,просп. Ленина, 4', 'court_time_shift': 0,
           'court_phone_info': '(835-2)62-40-30', 'court_fax_info': '(835-2)62-54-00',
           'court_email': 'chuvashia.info@arbitr.ru', 'court_website': 'http://chuvashia.arbitr.ru/',
           'court_head': 'И.о. Филиппов Борис Николаевич'},
          {'court_name': 'Арбитражного суда Чукотского автономного округа', 'court_code': 'А80',
           'court_address': '689000 Чукотский АО, г. Анадырь,ул. Ленина, 9а', 'court_time_shift': 8,
           'court_phone_info': '(427-22)2-96-00', 'court_fax_info': '(427-22)2-29-69',
           'court_email': 'info@chukotka.arbitr.ru', 'court_website': 'http://chukotka.arbitr.ru/',
           'court_head': 'Дерезюк Юлия Владимировна'},
          {'court_name': 'Арбитражного суда Ямало-Ненецкого автономного округа', 'court_code': 'А81',
           'court_address': '629007 Ямало-Ненецкий АО, Салехард,ул. Республики, 102', 'court_time_shift': 2,
           'court_phone_info': '(34922)5-31-77 - канцелярия(34922)5-31-00 - автосекретарь',
           'court_fax_info': '(34922)5-31-53', 'court_email': 'info@yamal.arbitr.ru',
           'court_website': 'http://yamal.arbitr.ru/', 'court_head': 'Слесарев Андрей Алексеевич'},
          {'court_name': 'Арбитражного суда Ярославской области', 'court_code': 'А82',
           'court_address': '150999, Ярославль,просп. Ленина, 28', 'court_time_shift': 0,
           'court_phone_info': '(485-2)281-182', 'court_fax_info': '', 'court_email': 'info@yaroslavl.arbitr.ru',
           'court_website': 'http://yaroslavl.arbitr.ru/', 'court_head': 'Гущев Владимир Владимирович'},
          {'court_name': 'Первый арбитражного апелляционный суда', 'court_code': '01АП',
           'court_address': '600017, г. Владимирул.Березина, д.4', 'court_time_shift': 0,
           'court_phone_info': '(4922)44-76-65', 'court_fax_info': '(4922)44-73-10',
           'court_email': 'info@1aas.arbitr.ru', 'court_website': 'http://1aas.arbitr.ru/',
           'court_head': 'Бондарь Андрей Николаевич'},
          {'court_name': 'Второй арбитражного апелляционный суда', 'court_code': '02АП',
           'court_address': '610007 г. Киров,ул.  Хлыновская, д. 3', 'court_time_shift': 0,
           'court_phone_info': '(833-2)519-100(833-2)519-109 - телефон справочно-информационной службы(833-2)519-119 - телефон доверия',
           'court_fax_info': '(833-2)519-200', 'court_email': 'info@2aas.arbitr.ru',
           'court_website': 'http://2aas.arbitr.ru/', 'court_head': 'Устюжанинов Владимир Анатольевич'},
          {'court_name': 'Третий арбитражного апелляционный суда', 'court_code': '03АП',
           'court_address': '660049, г. Красноярскул. Ленина, д. 1Б', 'court_time_shift': 4,
           'court_phone_info': '(391)222-11-00', 'court_fax_info': '(391)212-14-50',
           'court_email': 'info@3aas.arbitr.ru', 'court_website': 'http://3aas.arbitr.ru/',
           'court_head': 'Зуев Андрей Олегович'},
          {'court_name': 'Четвертый арбитражного апелляционный суда', 'court_code': '04АП',
           'court_address': '672000, г.Чита,ул. Ленина, 100-б', 'court_time_shift': 6,
           'court_phone_info': '(302-2)35-71-28(302-2)35-96-26', 'court_fax_info': '(302-2)35-70-85',
           'court_email': 'info@4aas.arbitr.ru', 'court_website': 'http://4aas.arbitr.ru/',
           'court_head': 'Доржиев Эрдэм Петрович'},
          {'court_name': 'Пятый арбитражного апелляционный суда', 'court_code': '05АП',
           'court_address': '690001, Приморский край, г. Владивостокул. Светланская, 115', 'court_time_shift': 7,
           'court_phone_info': '(4232)210-901(4232)210-909', 'court_fax_info': '(4232)210-969(4232)210-998',
           'court_email': '5aas.info@arbitr.ru', 'court_website': 'http://5aas.arbitr.ru/',
           'court_head': 'Зимин Евгений Викторович'},
          {'court_name': 'Шестой арбитражного апелляционный суда', 'court_code': '06АП',
           'court_address': '680000, г. Хабаровскул. Пушкина, 45', 'court_time_shift': 7,
           'court_phone_info': '(4212)30-00-25', 'court_fax_info': '(4212)30-28-16(4212)39-08-94',
           'court_email': 'info@6aas.arbitr.ru', 'court_website': 'http://6aas.arbitr.ru/',
           'court_head': 'Кривощёков Андрей Владимирович'},
          {'court_name': 'Седьмой арбитражного апелляционный суда', 'court_code': '07АП',
           'court_address': '634050, г. ТомскНабережная реки Ушайки, д. 24', 'court_time_shift': 4,
           'court_phone_info': '(382-2)611-201(382-2)611-325 - отдел делопроизводства(382-2)611-214 - отдел делопроизводства(382-2)611-224 - отдел делопроизводства',
           'court_fax_info': '(382-2)611-222', 'court_email': 'info@7aas.arbitr.ru',
           'court_website': 'http://7aas.arbitr.ru/', 'court_head': 'Дубинина Татьяна Николаевна'},
          {'court_name': 'Восьмой арбитражного апелляционный суда', 'court_code': '08АП',
           'court_address': '644024, г.Омскул. 10 лет Октября, д.42', 'court_time_shift': 3,
           'court_phone_info': '(3812)37-26-22', 'court_fax_info': '(3812)37-26-22',
           'court_email': 'info@8aas.arbitr.ru', 'court_website': 'http://8aas.arbitr.ru/',
           'court_head': 'Фролова Светлана Викторовна'},
          {'court_name': 'Девятый арбитражного апелляционный суда', 'court_code': '09АП',
           'court_address': '127994,  г.Москва,проезд Соломенной Сторожки, д. 12', 'court_time_shift': 0,
           'court_phone_info': '(495)987-28-00', 'court_fax_info': '(495)987-28-11',
           'court_email': '9aas.info@arbitr.ru', 'court_website': 'http://9aas.arbitr.ru/',
           'court_head': 'Гладков Игорь Евгеньевич'},
          {'court_name': 'Десятый арбитражного апелляционный суда', 'court_code': '10АП',
           'court_address': '117997, г. Москва,ул. Садовническая, д. 68/70, стр. 1', 'court_time_shift': 0,
           'court_phone_info': '(495)987-27-53(495)987-27-15(495)987-27-22', 'court_fax_info': '(495)987-27-13',
           'court_email': '10aas.info@arbitr.ru', 'court_website': 'http://10aas.arbitr.ru/',
           'court_head': 'Воробьева Инна Олеговна'},
          {'court_name': 'Одиннадцатый арбитражного апелляционный суда', 'court_code': '11АП',
           'court_address': '443070, г. СамараУл.Аэродромная, д.11А', 'court_time_shift': 1,
           'court_phone_info': '(846)372-62-62 - приемная председателя судаа(846)372-62-06 - пресс - секретарь(846)273-36-45 - справочно-информационная служба(846)372-62-54 - справочно-информационная служба',
           'court_fax_info': '(846)372-62-54', 'court_email': 'info@11aas.arbitr.ru',
           'court_website': 'http://11aas.arbitr.ru/', 'court_head': 'Сафаева Наиля Равильевна'},
          {'court_name': 'Двенадцатый арбитражного апелляционный суда', 'court_code': '12АП',
           'court_address': '410002 г.Саратов,ул. Лермонтова, д.30, к.2', 'court_time_shift': 1,
           'court_phone_info': '8-800-200-1277(8452) 74-90-90', 'court_fax_info': '(8452) 74-90-91',
           'court_email': 'info@12aas.arbitr.ru', 'court_website': 'http://12aas.arbitr.ru/',
           'court_head': 'Шараев Сергей Юрьевич'},
          {'court_name': 'Тринадцатый арбитражного апелляционный суда', 'court_code': '13АП',
           'court_address': '191015 г.Санкт-Петербург,юридический - Суворовский пр., д.50/52;  фактический - Суворовский пр., д.65',
           'court_time_shift': 0, 'court_phone_info': '(812)647-59-99', 'court_fax_info': '(812)647-59-96',
           'court_email': 'info@13aas.arbitr.ru', 'court_website': 'http://13aas.arbitr.ru/',
           'court_head': 'Изотова Светлана Валерьевна'},
          {'court_name': 'Четырнадцатый арбитражного апелляционный суда', 'court_code': '14АП',
           'court_address': '160001, г. Вологдаул. Батюшкова, д.12', 'court_time_shift': 0,
           'court_phone_info': '(8172)78-09-14(8172)78-09-16', 'court_fax_info': '(8172)72-84-68',
           'court_email': 'info@14aas.arbitr.ru', 'court_website': 'http://14aas.arbitr.ru/',
           'court_head': 'Потеева Анжела Валерьевна'},
          {'court_name': 'Пятнадцатый арбитражного апелляционный суда', 'court_code': '15АП',
           'court_address': '344002, г. Ростов-на-Донупер. Газетный, 34', 'court_time_shift': 0,
           'court_phone_info': '(863)218-60-01(863)218-60-26', 'court_fax_info': '(863)218-60-27',
           'court_email': 'info@15aas.arbitr.ru', 'court_website': 'http://15aas.arbitr.ru/',
           'court_head': 'Авдонина Ольга Геннадьевна'},
          {'court_name': 'Шестнадцатый арбитражного апелляционный суда', 'court_code': '16АП',
           'court_address': '357600, Ставропольский край, г.Ессентукиул. Вокзальная д.2', 'court_time_shift': 0,
           'court_phone_info': '(87934)6-29-62', 'court_fax_info': '(87934)6-09-14',
           'court_email': 'info@16aas.arbitr.ru', 'court_website': 'http://16aas.arbitr.ru/',
           'court_head': 'Токарева Марина Владимировна'},
          {'court_name': 'Семнадцатый арбитражного апелляционный суда', 'court_code': '17АП',
           'court_address': '614068 г.Пермьул.Пушкина, 112', 'court_time_shift': 2,
           'court_phone_info': '(342)230-78-01', 'court_fax_info': '(342)230-78-58',
           'court_email': '17aas.info@ARBITR.RU', 'court_website': 'http://17aas.arbitr.ru/',
           'court_head': 'Беляев Константин Петрович'},
          {'court_name': 'Восемнадцатый арбитражного апелляционный суда', 'court_code': '18АП',
           'court_address': '454080, Челябинскпр. Ленина, 83', 'court_time_shift': 2,
           'court_phone_info': '(351)259-66-20(351)259-66-18', 'court_fax_info': '(351)259-66-15',
           'court_email': '18ap.info@arbitr.ru', 'court_website': 'http://18aas.arbitr.ru',
           'court_head': 'Крашенинников Дмитрий Сергеевич'},
          {'court_name': 'Девятнадцатый арбитражного апелляционный суда', 'court_code': '19АП',
           'court_address': '394018,  г. Воронеж,ул. Платонова, д.8', 'court_time_shift': 0,
           'court_phone_info': '(473)254-51-71(473)239-72-68', 'court_fax_info': '(473)254-51-03',
           'court_email': '19aas.info@arbitr.ru', 'court_website': 'http://19aas.arbitr.ru/',
           'court_head': 'Бумагин Александр Николаевич'},
          {'court_name': 'Двадцатый арбитражного апелляционный суда', 'court_code': '20АП',
           'court_address': '300041, г.Тулаул.Староникитская, д.1', 'court_time_shift': 0,
           'court_phone_info': '(4872)70-24-24(4872)36-32-71', 'court_fax_info': '(4872)36-20-09',
           'court_email': 'info@20aas.arbitr.ru', 'court_website': 'http://20aas.arbitr.ru/',
           'court_head': 'Сурков Дмитрий Леонидович'},
          {'court_name': 'Двадцать первый арбитражного апелляционный суда', 'court_code': '21АП',
           'court_address': '299011 г. Севастопольул. Суворова, 21', 'court_time_shift': 0,
           'court_phone_info': '(8692)54-74-95', 'court_fax_info': '(8692)54-74-95',
           'court_email': 'info@21aas.arbitr.ru', 'court_website': 'http://21aas.arbitr.ru/',
           'court_head': 'Латынин Олег Анатольевич'},
          {'court_name': 'Волго-Вятский арбитражного округ', 'court_code': 'Ф01',
           'court_address': '603082 Нижний Новгород,Кремль, корп. 4', 'court_time_shift': 0,
           'court_phone_info': '(831)419-27-33(831)439-00-20(831)8-910-385-09-52', 'court_fax_info': '(831)439-14-42',
           'court_email': 'info@fasvvo.arbitr.ru', 'court_website': 'http://fasvvo.arbitr.ru/',
           'court_head': 'Толмачёв Андрей Анатольевич'},
          {'court_name': 'Восточно-Сибирский арбитражного округ', 'court_code': 'Ф02',
           'court_address': '664025 Иркутск,ул. Чкалова, 14', 'court_time_shift': 5,
           'court_phone_info': '(3952)214-860 - приемная(3952)214-884 - отдел делопроизводства(3952)214-865 - отдел делопроизводства(3952)214-894 - отдел делопроизводства',
           'court_fax_info': '(3952)210-164 - приемная(3952)210-170 - отдел делопроизводства(3952)210-171 - отдел делопроизводства(3952)210-172 - отдел делопроизводства(3952)214-174 - отдел кадров',
           'court_email': 'info@fasvso.arbitr.ru', 'court_website': 'http://fasvso.arbitr.ru/',
           'court_head': 'Антонова Светлана Александровна'},
          {'court_name': 'Дальневосточный арбитражного округ', 'court_code': 'Ф03',
           'court_address': '680000 Хабаровск,ул. Пушкина, 45', 'court_time_shift': 7,
           'court_phone_info': '(421-2)30-22-54(421-2)45-95-24', 'court_fax_info': '(421-2)31-37-65',
           'court_email': 'info@fasdvo.arbitr.ru', 'court_website': 'http://fasdvo.arbitr.ru/',
           'court_head': 'Солодилов Андрей Владимирович'},
          {'court_name': 'Западно-Сибирский арбитражного округ', 'court_code': 'Ф04',
           'court_address': '625010 Тюмень,ул. Ленина, 74', 'court_time_shift': 2,
           'court_phone_info': '(3452)799-555(3452)799-444', 'court_fax_info': '',
           'court_email': 'info@faszso.arbitr.ru', 'court_website': 'http://faszso.arbitr.ru/',
           'court_head': 'Иванов Владислав Анатольевич'},
          {'court_name': 'Московский арбитражного округ', 'court_code': 'Ф05',
           'court_address': '127994, Москва, ГСП-4ул. Селезневская, д. 9,', 'court_time_shift': 0,
           'court_phone_info': '(495)609-57-75', 'court_fax_info': '(495)609-57-65',
           'court_email': 'info@fasmo.arbitr.ru', 'court_website': 'http://fasmo.arbitr.ru/',
           'court_head': 'Кресс Вячеслав Викторович'},
          {'court_name': 'Поволжский арбитражного округ', 'court_code': 'Ф06',
           'court_address': '420066 Республика Татарстан, Казань,ул. Красносельская, д. 20', 'court_time_shift': 0,
           'court_phone_info': '(843)291-04-13, 291-04-15', 'court_fax_info': '(843)291-04-79',
           'court_email': 'info@faspo.arbitr.ru', 'court_website': 'http://faspo.arbitr.ru/',
           'court_head': 'Глазов Юрий Владимирович'},
          {'court_name': 'Северо-Западный арбитражного округ', 'court_code': 'Ф07',
           'court_address': '190121, г. Санкт-Петербург,ул. Якубовича, д.4', 'court_time_shift': 0,
           'court_phone_info': '(812)312-82-96', 'court_fax_info': '(812)571-47-47',
           'court_email': 'asinfo@fasszo.spb.ru', 'court_website': 'http://fasszo.arbitr.ru/',
           'court_head': 'Маркин Сергей Федорович'},
          {'court_name': 'Северо-Кавказский арбитражного округ', 'court_code': 'Ф08',
           'court_address': '350063 Краснодар,ул. Рашпилевская, д.4', 'court_time_shift': 0,
           'court_phone_info': '(861)201-34-00(861)267-26-56', 'court_fax_info': '(861)268-44-98(861)201-34-06',
           'court_email': 'info@fassko.arbitr.ru', 'court_website': 'http://fassko.arbitr.ru/',
           'court_head': 'Захаров Владимир Викторович'},
          {'court_name': 'Уральский арбитражного округ', 'court_code': 'Ф09',
           'court_address': '620075 Екатеринбургпросп. Ленина, 32/27', 'court_time_shift': 2,
           'court_phone_info': '(343)359-86-41 - (процессуальные вопросы) - отдел делопроизводства(343)311-16-90 - (общие вопросы) - секретарь приемной',
           'court_fax_info': '(343)311-16-78', 'court_email': 'asuo.info@arbitr.ru',
           'court_website': 'http://fasuo.arbitr.ru/', 'court_head': 'Решетникова Ирина Валентиновна'},
          {'court_name': 'Центральный арбитражного округ', 'court_code': 'Ф10',
           'court_address': '248001 г. Калуга,ул. Кирова д.4', 'court_time_shift': 0,
           'court_phone_info': '(4842)71-33-33', 'court_fax_info': '(4842)22-28-08',
           'court_email': 'info@fasco.arbitr.ru', 'court_website': 'http://fasco.arbitr.ru/',
           'court_head': 'Орлов Александр Владимирович'}]

courts = {i["court_code"]: i for i in courts}
